# Use Java 21 base image
FROM eclipse-temurin:21-jdk

# Create app directory
WORKDIR /app

# Copy everything to container
COPY . .

# Build the project using Maven
RUN ./mvnw clean package -DskipTests

# Expose port (change if your app uses something else)
EXPOSE 8080

# Run the app
CMD ["java", "-jar", "target/*.jar"]
